// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2C2PkAz2kY1FrNNldHfWgnM8_s0yosZs',
    appId: '1:240476768010:web:821e9107a15e30ef725cf3',
    messagingSenderId: '240476768010',
    projectId: 'ssip-database',
    authDomain: 'ssip-database.firebaseapp.com',
    storageBucket: 'ssip-database.appspot.com',
    measurementId: 'G-3W45Z0S7MH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtqraq-IB0MvJlWn92gf8zBgiGX0egXvg',
    appId: '1:240476768010:android:4bd0f526acaa319d725cf3',
    messagingSenderId: '240476768010',
    projectId: 'ssip-database',
    storageBucket: 'ssip-database.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgS6o1T1NQQx-l4slckqSFxNdQJh5SQfE',
    appId: '1:240476768010:ios:10e541104893d8b6725cf3',
    messagingSenderId: '240476768010',
    projectId: 'ssip-database',
    storageBucket: 'ssip-database.appspot.com',
    iosClientId: '240476768010-bsstsqs5scv8lp5mpuia0q6g0kkq4c91.apps.googleusercontent.com',
    iosBundleId: 'com.example.jskApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgS6o1T1NQQx-l4slckqSFxNdQJh5SQfE',
    appId: '1:240476768010:ios:10e541104893d8b6725cf3',
    messagingSenderId: '240476768010',
    projectId: 'ssip-database',
    storageBucket: 'ssip-database.appspot.com',
    iosClientId: '240476768010-bsstsqs5scv8lp5mpuia0q6g0kkq4c91.apps.googleusercontent.com',
    iosBundleId: 'com.example.jskApp',
  );
}
